from time import sleep
print('-=-'*10)
print('Escolha um número : ')
opção = int(input())
print('-=-'*10)
sleep(2)
print('--Calculando--')
print('-=-'*10)
sleep(1)
print('{} x 1 = {}'.format(opção,(opção*1)))
print('{} x 2 = {}'.format(opção,(opção*2)))
print('{} x 3 = {}'.format(opção,(opção*3)))
print('{} x 4 = {}'.format(opção,(opção*4)))
print('{} x 5 = {}'.format(opção,(opção*5)))
print('{} x 6 = {}'.format(opção,(opção*6)))
print('{} x 7 = {}'.format(opção,(opção*7)))
print('{} x 8 = {}'.format(opção,(opção*8)))
print('{} x 9 = {}'.format(opção,(opção*9)))
print('{} x 10 = {}'.format(opção,(opção*10)))

print('Fim')
